#====================================================================================================================
#====================================================================================================================
#                                   Autogenerated FullMonte Simulation TCL Script                                    
# When modifying this file, please carefully follow the instractions for each section to ensure a successful run.    
#====================================================================================================================
#====================================================================================================================
package require FullMonte

#====================================================================================================================
#                              Simulation Progress Tracker (please do not modify)                                    
#====================================================================================================================
proc progressTimer {} {
    while { ![k done] } {
        puts -nonewline [format "\rProgress %6.2f%%" [expr 100.0*[k progressFraction]]]
        flush stdout
        after 200
    }
    puts [format "\rProgress %6.2f%%" 100.0]
}

#====================================================================================================================
#                                   Input VTK File Path (please do not modify)                                       
#====================================================================================================================
set fn "/sims/Colin27_tagged_tumor_1.mesh_64Rx7pI.vtk"

VTKMeshReader R
    R filename $fn
    R read

#====================================================================================================================
#                                                  Mesh Geometry                                                     
# The "unitDimension" function is optional. If you would like to specify the unit of your mesh, which can be cm or   
# mm, please do so with this function. This template uses the unit from your simulation settings, but you may        
# modify it if appropriate.                                                                                          
#====================================================================================================================
set M [R mesh]
$M unitDimension "mm"

#====================================================================================================================
#                                                Region Materials                                                    
# Please define your region materials here. Air is always Region 0, and an example usage is provided below. Please   
# specify the material properties in order that matches the region IDs in the supplied mesh. If the mesh unit was    
# previously specified, you must specify the material units as well (should be consistant with the mesh unit).       
#====================================================================================================================
MaterialSet MS

Material air 
    air    unitDimension    "mm"
    air    scatteringCoeff    0.0
    air    absorptionCoeff    0.0
    air    refractiveIndex    1.0
    air    anisotropy    0.0

Material examplematerial 
    examplematerial    unitDimension    "mm"
    examplematerial    scatteringCoeff    0.1
    examplematerial    absorptionCoeff    0.2
    examplematerial    refractiveIndex    1.2
    examplematerial    anisotropy    0.1

MS exterior air
MS append examplematerial

#====================================================================================================================
#                                                Light Source(s)                                                     
# Please define your light source type and their positions on the mesh (make sure the coordinates are scaled to      
# match the mesh unit, if specified. Supported light source types include: Point, PencilBeam, Volume, Ball,          
# Cylinder, and SurfaceSourceBuilder.                                                                                
#====================================================================================================================
Point P1
    P1 position "-2.5 20.0 1400.0"
    P1 power 1

#====================================================================================================================
#                                                     Kernel                                                         
# This is autogenerated from your simulation settings. You may modify if you would like to use a different kernel    
# type. Choices are: TetraSVKernel, TetraSurfaceKernel, TetraVolumeKernel, TetraInternalKernel, and                  
# TetraCUDAInternalKernel. Optionally, the amount and type (power/energy) that is represented by the total photon    
# packets can be specifie in the "energyPowerValue" and "isEnergy_or_Power" functions, respectively.                 
#====================================================================================================================
TetraSVKernel k
    k packetCount 1000000
    k geometry $M
    k materials MS
    k isEnergy_or_Power "W"
    k energyPowerValue 10.0
    k source P1

#====================================================================================================================
#                                   Simulation Start (please do not modify)                                          
#====================================================================================================================
    k startAsync
    progressTimer
    k finishAsync

#====================================================================================================================
#                                  Simulation Results (please do not modify)                                         
#====================================================================================================================
set ODC [k results]

#====================================================================================================================
#                                           Energy to Fluence Converter                                              
# This section of the template converts the simulation results of volume energy to fluence values (Energy/area, such 
# as J/mm^2). You may modify for your different conversion needs. The choices for                                    
# Input include: inputPhotonWeight (raw results from simulation - unit-less),                                        
#                 inputEnergy (PhotonWeight*TotalEnergy/TotalPackets - in Joules (J) or Watt (W)),                   
#                 inputFluence (Energy/Area or Energy/Volume/muA - in W/mm^2, W/cm^2, J/mm^2, or J/cm^2), and        
#                 inputEnergyPerVolume (Energy/Volume - in W/mm^3, W/cm^3, J/mm^3, or J/cm^3.                        
# Output include: outputPhotonWeight, outputFluence, outputEnergy, and outputEnergyPerVolume.                        
#====================================================================================================================
EnergyToFluence EF
    EF kernel k
    EF inputPhotonWeight
    EF data [$ODC getByName "VolumeEnergy"]
    EF outputFluence
    EF update

#====================================================================================================================
#                                               Output Mesh Writer                                                   
# This section of the template generates an output VTK that contains fluence values of the volume. By default, it is 
# named after the input mesh with a ".out.vtk" extension. You may modify this path or generate multiple output VTKs  
# as long as you start the path names with "/sims/" directory and no subdirectories.                                 
#    Example 1: "/sims/example_output_mesh.vtk" is ok                                                                
#    Example 2: "example_output_mesh.vtk" is NOT ok                                                                  
#    Example 3: "/sims/example_subdir/example_output_mesh.vtk" is NOT ok                                             
# Please note that the DVH generator only looks for the default path, so you would not be able to automatically view 
# the DVH if you modify the file paths here. However, you can still manually download the output VTKs and upload them
# back to the Visualization page to view their DVH. You can also use the 3D Visualizor in any case: if the default   
# file name is not found, your Root folder will be loaded to the ParaView application, and you can find your desired 
# mesh by browsing through the Root folder.                                                                          
#====================================================================================================================
VTKMeshWriter W
    W filename "/sims/Colin27_tagged_tumor_1.mesh_PeB9UG8.out.vtk"
    W addData "Fluence" [EF result]
    W mesh $M
    W addHeaderComment "MeshUnit: mm EnergyUnit: W"
    W write

#====================================================================================================================
#                                              Fluence Matrix Writer                                                 
# This section of the template writes fluence values of the volume into a simple text file. By default, it is named  
# after the input mesh with a ".phi_v.txt" extension. You may modify its path or generate multiple output TXTs as    
# long as you start the path names with "/sims/" directory and no subdirectories. You may also discard this section. 
#    Example 1: "/sims/example_output_fluence.txt" is ok                                                             
#    Example 2: "example_output_fluence.txt" is NOT ok                                                               
#    Example 3: "/sims/example_subdir/example_output_fluence.txt" is NOT ok                                          
#====================================================================================================================
TextFileMatrixWriter TW
    TW filename "/sims/Colin27_tagged_tumor_1.mesh_PeB9UG8.phi_v.txt"
    TW source [EF result]
    TW write

