# Generated by Django 3.0.4 on 2020-03-10 06:04

import application.storage_backends
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50)),
                ('scattering_coeff', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('absorption_coeff', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('refractive_index', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('anisotropy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='preset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presetMesh', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('layerDesc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tclInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meshFile', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('kernelType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tclScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
            ],
        ),
    ]
