# Generated by Django 3.0.4 on 2021-01-13 02:17

import application.storage_backends
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50)),
                ('scattering_coeff', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('absorption_coeff', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('refractive_index', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('anisotropy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='preset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presetMesh', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('layerDesc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='visualizeMesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outputMeshFile', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('user', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tclScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('user', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tclInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meshFile', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('kernelType', models.CharField(max_length=255)),
                ('packetCount', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='simulationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_type', models.CharField(max_length=250)),
                ('tcl_script_path', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('mesh_file_path', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('output_vtk_path', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('output_txt_path', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('output_dvh_path', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('simulation_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='processRunning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
                ('pid', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fullmonteOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outputVtk', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('outputFluence', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('user', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='awsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNS', models.CharField(max_length=250)),
                ('pemfile', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('TCP_port', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(8000), django.core.validators.MaxValueValidator(8999)])),
                ('user', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
