# Generated by Django 3.0.4 on 2021-01-15 08:43

import application.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdtPresetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_list', models.CharField(max_length=1024)),
                ('mesh_list', models.CharField(max_length=1024)),
                ('opt_addr', models.CharField(max_length=1024)),
                ('mesh_addr', models.CharField(max_length=1024)),
                ('user', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='opFileInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_energy', models.CharField(max_length=64)),
                ('num_packets', models.CharField(max_length=64)),
                ('wave_length', models.CharField(max_length=64)),
                ('data_dir', models.CharField(max_length=255)),
                ('data_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=64)),
                ('tumor_weight', models.CharField(max_length=64)),
                ('placement_type', models.CharField(max_length=64)),
                ('opt_file', models.CharField(max_length=255)),
                ('light_source_file', models.CharField(max_length=255)),
                ('placement_file', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('user', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
