# Generated by Django 3.2.18 on 2023-03-10 04:17

import application.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tclinput',
            name='meshFile',
            field=models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
