# Generated by Django 2.2.6 on 2020-01-12 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tclinput',
            name='meshFile',
            field=models.FileField(upload_to='application/mesh'),
        ),
        migrations.CreateModel(
            name='Optical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50)),
                ('property_value', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Material')),
            ],
        ),
    ]
