# Generated by Django 3.0.4 on 2020-03-11 05:33

import application.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_tclinput_packetcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='fullmonteOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outputVtk', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('outputFluence', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
            ],
        ),
    ]
