# Generated by Django 2.2.6 on 2020-01-30 19:46

import application.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_tclscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='preset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presetMesh', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='tclinput',
            name='meshFile',
            field=models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
