# Generated by Django 3.0.4 on 2021-01-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_opfileinput_pdtpresetdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fullmonteOutput',
        ),
    ]
