# Generated by Django 3.0.4 on 2021-01-28 22:39

import application.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_delete_fullmonteoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationhistory',
            name='originalMeshFileName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tclinput',
            name='originalMeshFileName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='meshFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meshFile', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('originalMeshFileName', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='simulationhistory',
            name='meshFileID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.meshFiles'),
        ),
        migrations.AddField(
            model_name='tclinput',
            name='meshFileID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.meshFiles'),
        ),
    ]
