# Generated by Django 3.0.4 on 2021-01-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_delete_fullmonteoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='meshfileinfo',
            name='maxFluence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
