# Generated by Django 3.0.4 on 2020-03-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200130_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='layerDesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
