# Generated by Django 3.0.4 on 2021-01-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210128_1739'),
        ('application', '0004_meshfileinfo_maxfluence'),
    ]

    operations = [
    ]
