# Generated by Django 3.0.4 on 2021-02-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20210210_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='tclinput',
            name='scoredVolumeRegionID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
