# Generated by Django 3.0.4 on 2021-03-11 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_tclinput_scoredvolumeregionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tclinput',
            name='energyUnit',
            field=models.CharField(default='J', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tclinput',
            name='meshUnit',
            field=models.CharField(default='cm', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tclinput',
            name='totalEnergy',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
