# Generated by Django 3.0.4 on 2021-03-11 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20210311_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_unit',
            field=models.CharField(default='cm', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='awsfile',
            name='TCP_port',
            field=models.IntegerField(default='8080', validators=[django.core.validators.MinValueValidator(8000), django.core.validators.MaxValueValidator(8999)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='absorption_coeff',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='anisotropy',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='refractive_index',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='scattering_coeff',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
