# Generated by Django 3.0.4 on 2021-03-30 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_pdtouputlogfile'),
        ('application', '0009_auto_20210311_0845'),
    ]

    operations = [
    ]
