# Generated by Django 3.0.4 on 2021-05-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_merge_20210329_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdtpresetdata',
            name='mesh_addr',
            field=models.CharField(max_length=10240),
        ),
        migrations.AlterField(
            model_name='pdtpresetdata',
            name='mesh_list',
            field=models.CharField(max_length=10240),
        ),
        migrations.AlterField(
            model_name='pdtpresetdata',
            name='opt_addr',
            field=models.CharField(max_length=10240),
        ),
        migrations.AlterField(
            model_name='pdtpresetdata',
            name='opt_list',
            field=models.CharField(max_length=10240),
        ),
    ]
