# Generated by Django 3.0.4 on 2021-06-11 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20210503_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tclinput',
            name='scoredVolumeRegionID',
        ),
    ]
