# Generated by Django 3.0.4 on 2021-10-06 05:02

import application.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_remove_tclinput_scoredvolumeregionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='opfileinput',
            name='mesh_file_storage',
            field=models.FileField(blank=True, null=True, storage=application.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='opfileinput',
            name='opt_file_storage',
            field=models.FileField(blank=True, null=True, storage=application.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='opfileinput',
            name='tissue_property_file_storage',
            field=models.FileField(blank=True, null=True, storage=application.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='opfileinput',
            name='data_dir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opfileinput',
            name='data_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opfileinput',
            name='opt_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
