# Generated by Django 3.0.4 on 2021-10-18 01:56

import application.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20211006_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='opfileinput',
            name='tissue_types_file_storage',
            field=models.FileField(blank=True, null=True, storage=application.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
