# Generated by Django 3.0.4 on 2021-11-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20211025_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tclinput',
            name='thresholdFluence',
        ),
        migrations.AlterField(
            model_name='meshfileinfo',
            name='thresholdFluence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
