# Generated by Django 3.0.4 on 2022-01-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20211105_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='meshfileinfo',
            name='powerAndScaling',
            field=models.TextField(blank=True, null=True),
        ),
    ]
