# Generated by Django 3.0.4 on 2023-02-04 17:35

import application.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_meshfileinfo_powerandscaling'),
    ]

    operations = [
        migrations.CreateModel(
            name='serverlessInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
                ('meshFile', models.FileField(storage=application.storage_backends.PublicMediaStorage(), upload_to='')),
            ],
        ),
    ]
