"""
Django settings for fullMonteWeb project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import django_heroku
from decouple import config, Csv

print("Executing fullmonte settings.py")

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

#auth
LOGIN_REDIRECT_URL='/'
LOGOUT_REDIRECT_URL = '/'

# Application definition

INSTALLED_APPS = [
    'application',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap4',
    'django_forms_bootstrap',
    'django_cleanup',
    'fullMonteWeb',
    'storages',
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = config('fullmonteuser')
EMAIL_HOST_PASSWORD = config('fullmontepassword')


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fullMonteWeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fullMonteWeb.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DB_NAME', 'postgres'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASS', 'sql'),
        'HOST': 'localhost',
        'PORT': '5432',
        # 'CONN_MAX_AGE': 100, # keep database connected for 100s, in order for the child process to connect
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Etc/GMT+5'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# Activate Django-Heroku.
django_heroku.settings(locals())

#AWS settings
# Mymy's settings belows
AWS_ACCESS_KEY_ID = 'AKIARY3JXKYCDMEVICXO'
AWS_SECRET_ACCESS_KEY =config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = "fullmonteweb-storage"
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_S3_MAX_MEMORY_SIZE = 32768

STATICFILES_DIRS = [
                    os.path.join(BASE_DIR, 'application/static'),
                    ]

AWS_PUBLIC_MEDIA_LOCATION = 'media/public'
DEFAULT_FILE_STORAGE = 'application.storage_backends.PublicMediaStorage'

AWS_PRIVATE_MEDIA_LOCATION = 'media/private'
PRIVATE_FILE_STORAGE = 'application.storage_backends.PrivateMediaStorage'

AWS_DEFAULT_ACL = None

# Constants for IBM COS values
IBM_COS_API_KEY_ID ="9v5q4cAWMilAZhq6Iz3NVNkg_swA1E8yRGyK81QFklG0"
IBM_COS_SERVICE_INSTANCE_CRN=config('IBM_COS_SERVICE_INSTANCE_CRN')
IBM_COS_AUTH_ENDPOINT="https://iam.bluemix.net/oidc/token"
IBM_COS_ENDPOINT_URL="https://s3.ca-tor.cloud-object-storage.appdomain.cloud"
IBM_COS_MESH_BUCKET_NAME='ece496-fullmontesw-bucket-mesh'
IBM_COS_TCL_BUCKET_NAME='ece496-fullmontesw-bucket-tcl'
IBM_COS_OUTPUT_BUCKET_NAME='ece496-fullmontesw-bucket-outputs'
IBM_COS_GENERATED_TCL_BUCKET_NAME='ece496-fullmontesw-bucket-emptygeneratedtcl'
COS_HMAC_ACCESS_KEY_ID = config('COS_HMAC_ACCESS_KEY_ID')
COS_HMAC_SECRET_ACCESS_KEY = config('COS_HMAC_SECRET_ACCESS_KEY')
SERVERLESS_PASSWORD = config('SERVERLESS_PASSWORD')
